name: uniride_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_app_check: ^0.4.1+2
  firebase_messaging: 16.0.4
  flutter_local_notifications: 17.2.2
  permission_handler: 11.3.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  emoji_picker_flutter: ^2.1.0
  record: ^6.1.2
  audioplayers: ^6.0.0
  path_provider: ^2.1.3
  cloud_functions: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
